// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDrm-5JX3Ak2Vpap3zTth4mTpf5uZKsQs',
    appId: '1:575643027877:web:9811e143c49e36972d804c',
    messagingSenderId: '575643027877',
    projectId: 'informa-d90fe',
    authDomain: 'informa-d90fe.firebaseapp.com',
    storageBucket: 'informa-d90fe.appspot.com',
    measurementId: 'G-GQMGRE8CX5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCJzeig6xujNPNe09wKMX3Q5QSdYpN3Sk',
    appId: '1:575643027877:android:cbde2238c7f9edcd2d804c',
    messagingSenderId: '575643027877',
    projectId: 'informa-d90fe',
    storageBucket: 'informa-d90fe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDUWT3R2lGNzFAfbMMf9ee427LJTttHys',
    appId: '1:575643027877:ios:2733316c9f20a15a2d804c',
    messagingSenderId: '575643027877',
    projectId: 'informa-d90fe',
    storageBucket: 'informa-d90fe.appspot.com',
    iosBundleId: 'com.example.informa3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDUWT3R2lGNzFAfbMMf9ee427LJTttHys',
    appId: '1:575643027877:ios:f7c06a38dfb673982d804c',
    messagingSenderId: '575643027877',
    projectId: 'informa-d90fe',
    storageBucket: 'informa-d90fe.appspot.com',
    iosBundleId: 'com.example.informa3.RunnerTests',
  );
}
